### ISSUE TITLE
File doesn't exist

### ISSUE THREAD

**Issue by marcus-no** [maltekrupa/docker-log.io-harvester#1]
Keep getting:
error: File doesn't exist: '/logs/apache2/error.log'
error: File doesn't exist: '/logs/apache2/access.log'

I've tried to change the config and mapping to see if that helped, but same error (with different paths ofc).

Suggestions?

**Comment by maltekrupa** [comment]
Hi marcus-no,

do the apache log files actually look like the provided filenames? What I mean is: Is there a file on you host located at `/var/log/apache2/error.log` or `/var/log/apache2/access.log`?
If not, you'll have to correct the `-v /var/log/apache2:/logs/apache2` part.

Regards
Malte
